# Generated by Django 3.0.7 on 2020-06-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VRCPubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('author', models.CharField(max_length=100)),
                ('link', models.URLField()),
                ('publishedAt', models.DateField()),
                ('isbn', models.CharField(max_length=100)),
            ],
        ),
    ]
