# Generated by Django 3.0.5 on 2020-06-08 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('VRCpubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrcpubs',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
