# Generated by Django 3.0.5 on 2020-06-09 05:27

import VRCpubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRCpubs', '0008_auto_20200609_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrcpubs',
            name='publishedAt',
            field=models.DateTimeField(validators=[VRCpubs.models.VRCPubs.present_or_past_date]),
        ),
    ]
