# Generated by Django 3.0.7 on 2020-06-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VRCpubs', '0009_auto_20200609_1057'),
        ('VRCpubs', '0004_auto_20200609_1706'),
    ]

    operations = [
    ]
