# Generated by Django 3.0.7 on 2020-06-12 08:29

import VRCpubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRCpubs', '0010_merge_20200612_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrcpubs',
            name='publishedAt',
            field=models.DateTimeField(validators=[VRCpubs.models.VRCPubs.present_or_past_date]),
        ),
    ]
